#version: '3.8'
name: arm-vatholm-prod
services:
  ### Docker-compose PostgreSQL сервер ###
  database:
    image: postgres:${POSTGRES_VERSION:-14.8}-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-pgs_arm_student}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bGGLgYqQJLDckv5H}
      POSTGRES_USER: ${POSTGRES_USER:-stasone}
    ports:
      - target: 5432
        published: 15432
        protocol: tcp
        mode: host
    volumes:
      - ${PWD}/.docker/postgresql/data:/var/lib/postgresql/data
    labels:
      com.symfony.server.service-prefix: 'DATABASE_URL'
    networks:
      - nginx-php-PSQL

  php82-service:
    build:
      context: .
      dockerfile: ${PWD}/.docker/dockerfiles/php/Dockerfile
    #   docker build --pull --rm -f "/root/php-arm/Dockerfile" -t phpfpm-arm-vatholm-ru:latest
    restart: always
    #image: phpfpm-arm-vatholm-ru:latest
    container_name: php82-container
    ports:
      - "9000:9000"
    volumes:
      - ${PWD}/app/arm-student-app:/var/www/project
      - ${PWD}/.docker/certs:/var/www/ssl-home/project
      - ${PWD}/.docker/supervisor:/etc/supervisor
      - ${PWD}/.docker/logs/supervisor:/var/log/supervisor/
    networks:
      - nginx-php-PSQL

  nginx-service:
    image: nginx:stable-alpine
    restart: always
    container_name: nginx-container
    ports:
      - "8080:80"
      - "1443:443"
    volumes:
      - .${PWD}/app/arm-student-app:/var/www/project
      - ${PWD}/.docker/logs/nginx:/var/log/nginx/
      - ${PWD}/.docker/certs:/var/www/ssl-home/project
      #- ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      #- ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - type: bind
        source: ./.docker/config/nginx/conf.d/default.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - php82-service
    networks:
      - nginx-php-PSQL




  ###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    restart: unless-stopped
    environment:
      SERVER_NAME: ':3000'
      MERCURE_PUBLISHER_JWT_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.7Hlt-ke43l49emcnOvsmMa2VUCKhJoZEj8j1zTP4PfM'
      MERCURE_SUBSCRIBER_JWT_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.7Hlt-ke43l49emcnOvsmMa2VUCKhJoZEj8j1zTP4PfM'
      CERT_FILE: '/var/www/ssl-home/project/ssl_cert.crt'
      DEBUG: 1
      KEY_FILE: '/var/www/ssl-home/project/ssl_key.key'
      MERCURE_EXTRA_DIRECTIVES: |
        auto_https off
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/.docker/certs:/var/www/ssl-home/project
      - mercure_data:/data
      - mercure_config:/config
    networks:
      - nginx-php-PSQL
###< symfony/mercure-bundle ###

volumes:
  ###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
  ###< symfony/mercure-bundle ###
  ###> doctrine/doctrine-bundle ###

  # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
  # - ./docker/db/data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###



networks:
  nginx-php-PSQL: